services:
  interactive_service:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket
      - ./03_maven_tutorial:/03_maven_tutorial  # Mount the directory as a volume
    privileged: true  # Run the container with privileged access
    command: sh -c "/usr/local/bin/jenkins_init.sh 4"
